### PR TITLE
LTP: Fix test case access02 issue

### LINKED ISSUE #598: Add ELF loading support to LKL
We want LKL to be able to load ELF executables and libraries using the `binfmt_elf_fpdic` format. This format supports the loading of regular ELF binaries on a non-MMU architecture. 

This means that LKL must be compiled with `CONFIG_ELFCORE` and `CONFIG_ BINFMT_ELF_FDPIC` support. For this, we must include missing architecture-specific header files for ELF support under `arch/lkl`.

### PR DESCRIPTION
**Pull request by shaikshavali1**
This test is failed because it is using sgx-lkl's unsupported
feature fork() and system() syscalls. Below two modifications
are performed.
    1. Disabled the subtest cases which invoke system() syscall to check execution access.
    2. Disabled/Commented forking of the child process.
    3. Added the code to run the test with nobody user on the same process.
 This patch will be reverted once Github issue is fixed https://github.com/lsds/sgx-lkl/issues/598

### CODE REVIEW

File: testcases/kernel/syscalls/access/access02.c [hunk 1]
```diff
@@ -153,13 +155,18 @@ static void verify_access(unsigned int n)
 	access_test(tc, "root");
 
 	/* test as nobody */
+#if 0
```
Comment (hukoyu) [inline testcases/kernel/syscalls/access/access02.c:161]: Add a comment here why we are disabling this code block and when we will enable back.
Add a TODO comment so that we can tarck

Comment (hukoyu) [reply testcases/kernel/syscalls/access/access02.c:161]: Are we running with nobody user? I thought we have issues running with nobody user that is why we were running with root user. Am I misunderstanding?

Comment (hukoyu) [reply testcases/kernel/syscalls/access/access02.c:161]: I didn't uderstand why we are running with nobody user? Are we reverting a change we made before?

**Review by hukoyu — CHANGES_REQUESTED** [review]
@shaikshavali1 please address my comments and answer my questions. Thanks

File: testcases/kernel/syscalls/access/access02.c (hunk 1 above)
Comment (shaikshavali1) [reply testcases/kernel/syscalls/access/access02.c:161]: > Add a comment here why we are disabling this code block and when we will enable back.
> Add a TODO comment so that we can tarck
 
Added the comment

Comment (shaikshavali1) [reply testcases/kernel/syscalls/access/access02.c:161]: > Are we running with nobody user? I thought we have issues running with nobody user that is why we were running with root user. Am I misunderstanding?

Yes, Test runs as nobody user as well. Yes, the test case performs the same sub-test in two user modes namely root and nobody.

Comment (shaikshavali1) [reply testcases/kernel/syscalls/access/access02.c:161]: > I didn't uderstand why we are running with nobody user? Are we reverting a change we made before?

The original test case is designed/implemented to run as nobody user and root user. No, we are not reverting any change.

**Comment by shaikshavali1** [comment]
@hukoyu, I addressed your comments could you please check the new patch.

**Review by hukoyu — APPROVED** [review]

**Review by davidchisnall — APPROVED** [review]
